// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Ved_MMBV0beMf7yZRtDEeZ9k7seHbh0',
    appId: '1:204436296304:android:ea067fff8e3a0675311ab5',
    messagingSenderId: '204436296304',
    projectId: 'crowdru-2',
    databaseURL: 'https://crowdru-2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crowdru-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTVmHSUhIW7QQv1QHAylTEg0mDn33oE4',
    appId: '1:204436296304:ios:3d1c258d47c3d590311ab5',
    messagingSenderId: '204436296304',
    projectId: 'crowdru-2',
    databaseURL: 'https://crowdru-2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crowdru-2.appspot.com',
    iosBundleId: 'com.example.crowdApp2',
  );
}
